/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author SHUBHAM
 */
public class ResultView2 extends javax.swing.JFrame {
    
    ResultView1 rv1=new ResultView1();
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;

   /* public ResultView2(String erol) 
    {
        System.out.println(erol);
    }*/    
    public ResultView2(String erol,String et) 
    {
        initComponents();
        //ResultView1 rv1=new ResultView1();
        
        eType.setText(et);
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","root");
            System.out.println("Connected");

            st = con.createStatement();
            
        } 
        catch (ClassNotFoundException e) 
        {
            System.out.println(e);
        } 
        catch (SQLException e) 
        {
            System.out.println(e);
        }
        
        try
        {
            String query="SELECT * from newuser where Enrollment_No='"+erol+"'";
            rs=st.executeQuery(query);
            System.out.println(query);
            while(rs.next())
            {
                enroll.setText(rs.getString(3));
                name.setText("Name : "+rs.getString(1));
                email.setText("E-mail : "+rs.getString(5));
                phone.setText("Phone No : "+rs.getString(4));
            }
            
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enrollment_No = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        enroll = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        eType = new javax.swing.JLabel();
        qAtempt = new javax.swing.JLabel();
        cAttempt = new javax.swing.JLabel();
        wAttempt = new javax.swing.JLabel();
        tMarks = new javax.swing.JLabel();
        aMarks = new javax.swing.JLabel();
        viewA = new javax.swing.JButton();
        aHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Enrollment_No.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Report Card");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 255));

        enroll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enroll.setText("Enrollment");

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setText("Name :");

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setText("E-mail :");

        phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phone.setText("Phone :");

        jDesktopPane1.setLayer(enroll, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(phone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        eType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eType.setForeground(new java.awt.Color(255, 0, 0));
        eType.setText("Exam Type");

        qAtempt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qAtempt.setText("Quetions Attempted");

        cAttempt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cAttempt.setText("Correct Attempts");

        wAttempt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wAttempt.setText("Wrong Attempts");

        tMarks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tMarks.setText("Total Marks");

        aMarks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aMarks.setText("Achieved Marks");

        viewA.setText("View Another Result");
        viewA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAActionPerformed(evt);
            }
        });

        aHome.setText("Admin Home");
        aHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aHomeActionPerformed(evt);
            }
        });

        Enrollment_No.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Enrollment_No.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Enrollment_No.setLayer(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Enrollment_No.setLayer(eType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Enrollment_No.setLayer(qAtempt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Enrollment_No.setLayer(cAttempt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Enrollment_No.setLayer(wAttempt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Enrollment_No.setLayer(tMarks, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Enrollment_No.setLayer(aMarks, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Enrollment_No.setLayer(viewA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Enrollment_No.setLayer(aHome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Enrollment_NoLayout = new javax.swing.GroupLayout(Enrollment_No);
        Enrollment_No.setLayout(Enrollment_NoLayout);
        Enrollment_NoLayout.setHorizontalGroup(
            Enrollment_NoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(Enrollment_NoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Enrollment_NoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Enrollment_NoLayout.createSequentialGroup()
                        .addGroup(Enrollment_NoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Enrollment_NoLayout.createSequentialGroup()
                                .addGroup(Enrollment_NoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qAtempt)
                                    .addComponent(cAttempt)
                                    .addComponent(wAttempt)
                                    .addComponent(tMarks)
                                    .addComponent(aMarks)
                                    .addGroup(Enrollment_NoLayout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel4)))
                                .addGap(0, 7, Short.MAX_VALUE))
                            .addComponent(eType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(Enrollment_NoLayout.createSequentialGroup()
                        .addComponent(viewA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(aHome)
                        .addGap(45, 45, 45))))
        );
        Enrollment_NoLayout.setVerticalGroup(
            Enrollment_NoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Enrollment_NoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(eType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(qAtempt)
                .addGap(18, 18, 18)
                .addComponent(cAttempt)
                .addGap(18, 18, 18)
                .addComponent(wAttempt)
                .addGap(18, 18, 18)
                .addComponent(tMarks)
                .addGap(18, 18, 18)
                .addComponent(aMarks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Enrollment_NoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewA)
                    .addComponent(aHome))
                .addGap(179, 179, 179)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Enrollment_No)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Enrollment_No)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAActionPerformed
        ResultView1 rv=new ResultView1();
        rv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewAActionPerformed

    private void aHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aHomeActionPerformed
        AdminHome ah=new AdminHome();
        ah.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_aHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ResultView2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Enrollment_No;
    private javax.swing.JButton aHome;
    private javax.swing.JLabel aMarks;
    private javax.swing.JLabel cAttempt;
    private javax.swing.JLabel eType;
    private javax.swing.JLabel email;
    private javax.swing.JLabel enroll;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel qAtempt;
    private javax.swing.JLabel tMarks;
    private javax.swing.JButton viewA;
    private javax.swing.JLabel wAttempt;
    // End of variables declaration//GEN-END:variables
}
